--  Schreier_Sims — Ada 2023 educational package for the Schreier–Sims
--  algorithm (Schreier 1927; Sims 1970).
--  Given generators of a finite permutation group G ≤ S_n, compute a base
--  and strong generating set (BSGS), the group order, and membership tests
--  via sifting through Schreier-tree transversals.
--  Primary source:
--  https://en.wikipedia.org/wiki/Schreier–Sims_algorithm
--  Sibling (README only; do not `with`): Todd–Coxeter (coset enumeration).

pragma Ada_2022;

package Schreier_Sims
  with SPARK_Mode => Off
is

   ------------------------------------------------------------------
   --  Educational capacity bounds
   ------------------------------------------------------------------

   Max_N : constant := 10;
   --  Points are labelled 1 .. N with N ≤ Max_N.

   Max_Generators : constant := 32;
   --  Input / strong-generator capacity (classroom bound).

   Max_Schreier : constant := 128;
   --  Temporary Schreier-generator buffer while building a level.

   ------------------------------------------------------------------
   --  Points and permutations
   ------------------------------------------------------------------

   subtype Point is Positive range 1 .. Max_N;

   --  Image(i) = i^g for i in 1 .. N. Entries beyond N are unused.
   type Image_Array is array (Point) of Point;

   type Permutation is record
      N     : Natural := 0;
      Image : Image_Array := [others => 1];
   end record;

   type Generator_List is array (Positive range <>) of Permutation;

   ------------------------------------------------------------------
   --  BSGS (base and strong generating set)
   ------------------------------------------------------------------

   type Orbit_Flags is array (Point) of Boolean;
   type Transversal_Array is array (Point) of Permutation;
   type Strong_Gen_Array is array (1 .. Max_Generators) of Permutation;

   --  One stabilizer-chain level G^{(i)} with base point Beta, orbit
   --  under the level's strong generators, and a transversal stored as
   --  full permutations (Schreier tree flattened): Beta^{U(p)} = p.
   type Level is record
      Beta       : Point := 1;
      Orbit_Size : Natural := 0;
      In_Orbit   : Orbit_Flags := [others => False];
      U          : Transversal_Array := [others => <>];
      Gen_Count  : Natural := 0;
      Gens       : Strong_Gen_Array := [others => <>];
   end record;

   type Level_Array is array (1 .. Max_N) of Level;

   --  Base = (Levels(1).Beta, ..., Levels(Length).Beta).
   --  Strong generators of G^{(i)} live in Levels(i).Gens.
   --  |G| = product of Levels(i).Orbit_Size.
   type BSGS is record
      N      : Natural := 0;
      Length : Natural := 0;
      Levels : Level_Array := [others => <>];
   end record;

   Invalid_Argument : exception;

   ------------------------------------------------------------------
   --  Basic permutation operations
   ------------------------------------------------------------------

   --  Identity on {1 .. N}. Raises Invalid_Argument if N not in 1 .. Max_N.
   function Identity (N : Positive) return Permutation
     with Global => null;

   --  Build a permutation from a full image map Img(1 .. N).
   --  Raises Invalid_Argument if N not in 1 .. Max_N or Img is not bijective.
   function Make_Permutation (Img : Image_Array; N : Positive) return Permutation
     with Global => null;

   --  Apply g to point x (requires 1 ≤ x ≤ g.N).
   function Apply (G : Permutation; X : Point) return Point
     with Global => null;

   --  Compose A then B: (A * B)(x) = B(A(x)). Degrees must match.
   function Compose (A, B : Permutation) return Permutation
     with Global => null;

   function Inverse (G : Permutation) return Permutation
     with Global => null;

   function Is_Identity (G : Permutation) return Boolean
     with Global => null;

   function Equal (A, B : Permutation) return Boolean
     with Global => null;

   ------------------------------------------------------------------
   --  Schreier–Sims
   ------------------------------------------------------------------

   --  Build a BSGS for the group generated by Generators.
   --  All generators must share the same degree N in 1 .. Max_N and be
   --  bijective. Raises Invalid_Argument on empty list, inconsistent
   --  degrees, or non-bijective maps. Identity-only lists yield the
   --  trivial group (Length = 0, Order = 1).
   function Build_BSGS (Generators : Generator_List) return BSGS
     with Global => null;

   --  |G| = product of orbit sizes along the stabilizer chain.
   function Order (G : BSGS) return Long_Long_Integer
     with Global => null;

   --  Membership test by sifting Perm through the Schreier transversals.
   --  Raises Invalid_Argument if Perm.N /= G.N.
   function Contains (G : BSGS; Perm : Permutation) return Boolean
     with Global => null;

   --  Number of base points (stabilizer-chain length).
   function Base_Length (G : BSGS) return Natural
     with Global => null;

   --  Base point at 1-based index I (1 .. Base_Length(G)).
   function Base_Point (G : BSGS; I : Positive) return Point
     with Global => null;

end Schreier_Sims;
